In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
a = np.array([1, 2, 3,4,5], ndmin = 2)
a

array([[1, 2, 3, 4, 5]])

In [ ]:
a = np.array([1, 2, 3], dtype = complex)
a

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
arr = np.array([1,2,3,4])

print(arr[0])


1


In [ ]:
#Get third and fourth elements from the following array and add them.
arr = np.array([1,2,3,4])

print(arr[2] +arr[3])


7


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0,1])

2nd element on 1st row:  2


In [ ]:
#Access the third element of the second array of the first array:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

print(arr[0,1,2])


6


In [ ]:
#Print the last element from the 2nd dim:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [ ]:
#Slice elements from index 1 to index 5 from the following array:

arr = np.array([1,2,3,4,5,6,7])

print(arr[1:5])

[2 3 4 5]


In [ ]:
#Slice elements from index 4 to the end of the array:
arr = np.array([1,2,3,4,5,6,7])

print(arr[4:])

[5 6 7]


In [ ]:
#Slice elements from the beginning to index 4 (not included):

arr = np.array([1,2,3,4,5,6,7])

print(arr[:4])

[1 2 3 4]


In [ ]:
#Return every other element from index 1 to index 5:

arr = np.array([1,2,3,4,5,6,7])

print(arr[1:5:2])

[2 4]


In [ ]:
#Return every other element from the entire array:
arr = np.array([1,2,3,4,5,6,7])

print(arr[::2])

[1 3 5 7]


In [ ]:
#Slice from the index 3 from the end to index 1 from the end:
arr = np.array([1,2,3,4,5,6,7])

print(arr[-3:-1])

[5 6]


In [ ]:
#From the second element, slice elements from index 1 to index 4 (not included):

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[1,1:4])

[7 8 9]


In [ ]:
#From both elements, return index 2:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[0:2,2])

[3 8]


In [ ]:
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
#int8, int16, int32, int64 can be replaced by equivalent string 'i1', 'i2','i4', etc.
import numpy as np

dt = np.dtype('i4')
dt

dtype('int32')

In [ ]:
#Get the data type of an array object:

arr = np.array([1,2,3,4])

print(arr.dtype)

int64


In [ ]:
#Get the data type of an array containing strings:

arr = np.array(['apple','banana','cherry'])

print(arr.dtype)

<U6


In [ ]:
#Create an array with data type 4 bytes integer:
arr = np.array([1,2,3,4],dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [ ]:
#Change data type from float to integer by using 'i' as parameter value:

arr = np.array([1.1,2.1,3.1])

newarr = arr.astype('i')
print(arr)
print(arr.dtype)
print(newarr)
print(newarr.dtype)

[1.1 2.1 3.1]
float64
[1 2 3]
int32


In [ ]:
#Change data type from integer to boolean:

arr = np.array([1,0,3])

newarr = arr.astype(bool)
print(arr)
print(arr.dtype)
print(newarr)
print(newarr.dtype)

[1 0 3]
int64
[ True False  True]
bool


In [ ]:
#Make a copy, change the original array, and display both arrays:
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] =42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
#Make a view, change the original array, and display both arrays:

arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] =42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
#Make a view, change the view, and display both arrays:

arr = np.array([1,2,3,4,5])
x = arr.view()
x[0] =31

print(arr)
print(x)
#The original array SHOULD be affected by the changes made to the view.

[31  2  3  4  5]
[31  2  3  4  5]


In [ ]:
#Print the value of the base attribute to check if an array owns it's data or not:
#The copy returns None.
#The view returns the original array.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)


None
[1 2 3 4 5]


In [ ]:
#Print the shape of a 2-D array:

arr = np.array([[1,2,3,4],[5,6,7,8]])

print(arr.shape)

(2, 4)


In [ ]:
#Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:

arr = np.array([1,2,3,4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [ ]:
#Convert the following 1-D array with 12 elements into a 2-D array.
#The outermost dimension will have 4 arrays, each with 3 elements:

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr = arr.reshape(4,3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#Convert the following 1-D array with 12 elements into a 3-D array.
#The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr = arr.reshape(2,3,2)

print(newarr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
#this is one dimensional array
import numpy as np
a = np.arange(24)
a.ndim

# now reshape it
b = a.reshape(2,4,3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [ ]:
x = np.arange(5)
x


array([0, 1, 2, 3, 4])

In [ ]:
# dtype set
x = np.arange(5, dtype = float)
x

array([0., 1., 2., 3., 4.])

In [ ]:
# start and stop parameters set
import numpy as np
x = np.arange(10,20,2)
x

array([10, 12, 14, 16, 18])

In [ ]:
# dtype of array is int8 (1 byte)
import numpy as np
x = np.array([1,2,3,4,5], dtype = np.int8)
x.itemsize

1

In [ ]:
# array of five zeros. Default dtype is float
import numpy as np
x = np.zeros(5)
x

array([0., 0., 0., 0., 0.])

In [ ]:
x = np.zeros((5,), dtype = np.int)
x

<ipython-input-40-e4f750252e37>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.zeros((5,), dtype = np.int)


array([0, 0, 0, 0, 0])

In [ ]:
# convert list to ndarray
import numpy as np

x = [1,2,3]
a = np.asarray(x)
a

array([1, 2, 3])

In [ ]:
# dtype is set
import numpy as np

x = [1,2,3]
a = np.asarray(x, dtype = float)
a

array([1., 2., 3.])

In [ ]:
#concatenation
import numpy as np
print('Concatenate two strings:')
print(np.char.add(['hello'],[' xyz']) )
print('\n')

print('Concatenation example:' )
print(np.char.add(['hello', 'hi'],[' abc', ' xyz']))


Concatenate two strings:
['hello xyz']


Concatenation example:
['hello abc' 'hi xyz']


In [ ]:
print(np.char.multiply('Hello ',3))


Hello Hello Hello 


In [ ]:
# np.char.center(arr, width,fillchar)
print(np.char.center('hello', 20,fillchar = '*'))

*******hello********


In [ ]:
#This function returns the copy of the string with the first letter capitalized.

print(np.char.capitalize('hello world'))


Hello world


In [ ]:
#This function returns a title cased version of the input string with the first letter of each word capitalized.

print(np.char.title('hello how are you?'))

Hello How Are You?


In [ ]:
print(np.char.lower(['HELLO','WORLD']) )
print(np.char.lower('HELLO'))

['hello' 'world']
hello


In [ ]:
print(np.char.upper('hello') )
print(np.char.upper(['hello','world']))

HELLO
['HELLO' 'WORLD']


In [ ]:
print(np.char.split ('hello how are you?'))
print (np.char.split ('TutorialsPoint,Hyderabad,Telangana', sep = ','))

['hello', 'how', 'are', 'you?']
['TutorialsPoint', 'Hyderabad', 'Telangana']


In [ ]:
#This method returns a string in which the individual characters are joined by separator character specified.

print (np.char.join(':','dmy') )
print (np.char.join([':','-'],['dmy','ymd']))

d:m:y
['d:m:y' 'y-m-d']


In [ ]:
#This function returns a new copy of the input string in which all occurrences of the sequence of characters is replaced by another given sequence.

print (np.char.replace ('He is a good boy', 'is', 'was'))

He was a good boy


In [ ]:
#Iterate on the elements of the following 1-D array:

arr = np.array([1,2,3])

for x in arr:
  print(x)

1
2
3


In [ ]:
#Iterate on the elements of the following 2-D array:
arr = np.array([[1,2,3], [4,5,6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [ ]:
#Iterate on each scalar element of the 2-D array:

arr = np.array([[1,2,3], [4,5,6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [ ]:
#Iterate on the elements of the following 3-D array:

arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
#Iterate down to the scalars:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
#The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.
#Iterating on Each Scalar Element
#In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

#Iterate through the following 3-D array:

arr = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [ ]:
#Join two arrays

arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
#Join two 2-D arrays along rows (axis=1):
arr1 = np.array([[1,2], [3,4]])

arr2 =np.array([[5,6], [7,8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
arr1 = np.array([1,2,3])

arr2 =np.array([4,5,6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
#Split the array in 3 parts:

arr = np.array([1,2,3,4,5,6])

newarr =np.array_split(arr,3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
#Access the splitted arrays:

arr = np.array([1,2,3,4,5,6])

newarr =np.array_split(arr,3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [ ]:
#Split the 2-D array into three 2-D arrays.

arr = np.array([[1,2], [3,4], [5,6], [7,8], [9,10], [11,12]])

newarr = np.array_split(arr,3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
#Split the 2-D array into three 2-D arrays along rows.

arr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12], [13,14,15], [16,17,18]])

newarr = np.array_split(arr,3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
#Find the indexes where the value is 4:

arr = np.array([1,2,3,4,5,4,4])

x =np.where(arr ==4)

print(x)

(array([3, 5, 6]),)


In [ ]:
#Find the indexes where the values are even:

arr = np.array([1,2,3,4,5,6,7,8])

x =np.where(arr%2==0)

print(x)

(array([1, 3, 5, 7]),)


In [ ]:
#The searchsorted() method is assumed to be used on sorted arrays.
#Find the indexes where the value 7 should be inserted:

arr = np.array([6,7,8,9])

x =np.searchsorted(arr,7)

print(x)

1


In [ ]:
#Find the indexes where the values 2, 4, and 6 should be inserted:

arr = np.array([1,3,5,7])

x =np.searchsorted(arr, [2,4,6])

print(x)

[1 2 3]


In [ ]:
#Sort the array:

arr = np.array([3,2,0,1])

print(np.sort(arr))

[0 1 2 3]


In [ ]:
#Sort the array alphabetically:

arr = np.array(['banana','cherry','apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [ ]:
#Sort a 2-D array:

arr = np.array([[3,2,4], [5,0,1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
